try{
}catch(Exceptions e){
System.out.println("exeptions founded");
}
